### ISSUE TITLE
Get all clients is not available

### ISSUE THREAD

**Issue by Saicheg** [wingrunr21/mindbody-api#20]
Hey!

According current MindBody API description to get all clients we need to do next SOAP request:

```
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://clients.mindbodyonline.com/api/0_5">
                <soapenv:Header/>
                <soapenv:Body>
                   <GetClients>
                      <Request>
                         <SourceCredentials>
                            <SourceName>{SourceName}</SourceName>
                            <Password>{Password}</Password>
                            <SiteIDs>
                               <int>{SiteID}</int>
                            </SiteIDs>
                         </SourceCredentials>
                         <UserCredentials>
                            <Username>{UserName}</Username>
                            <Password>{Password}</Password>
                            <SiteIDs>
                               <int>{SiteID}</int>
                            </SiteIDs>
                         </UserCredentials>
                         <XMLDetail>Basic</XMLDetail>
                         <PageSize>10</PageSize>
                         <CurrentPageIndex>0</CurrentPageIndex>
                         <SearchText></SearchText>
                      </Request>
                   </GetClients>
                </soapenv:Body>
             </soapenv:Envelope>
```

You can notice that comparing to other GetClients methods it does not have ClientIDs field on request body.

Current gem implementation have client_ids field required on get_clients action, which makes this API call impossible to write. Please see https://github.com/wingrunr21/mindbody-api/blob/master/lib/mindbody-api/services/client_service.rb#L8 for reference

Can we handle this somehow?

**Comment by daidekman** [comment]
Thanks again, @wingrunr21 for the great work on this. I know I'm 3 years late in joining and seeing these issues and I'm curious how the syntax was resolved to handle this one.

I see no results in the MindBody sandbox with this:
`MindBody::Service::ClientService.get_clients('')`

# { :clients => nil }

The [documentation](https://developers.mindbodyonline.com/Develop/ClientService) also indicates that UserCredentials must be passed for this call, so I'm curious how the syntax would be set to include those UserCredentials for .get_clients

And if I can be greedy with my questions, I ask @stevehanson how the syntax would work with a variable site_id, as in Issue #17 monkey patch solution.

Many thanks!

**Comment by zstrad44** [comment]
@daidekman  Did you happen to find the solution to this? I am just getting started with the MindBody sandbox, and I am running into the same issue with the `MindBody::Service::ClientService.get_clients('')` returning `# { :clients => nil }`

If you were able to figure this out, or if you could point me in the right direction, I would sure appreciate it!

**Comment by daidekman** [comment]
@zstrad44 It worked for me when adding .result at the end, so that it looks like this (for example):

Note: Replace 'abc' in all places with the terms that you need in your system.

 MindBody::Services::ClientService.get_clients('UserCredentials' => { 'Username' => 'abc', 'Password' => 'abc', 'SiteIDs' => { 'int' => [-99] } }, 'SearchText' => 'abc', site_id: -99).result

**Comment by Shivite** [comment]
how can we use the same credentials for two sites_id's. I want to show the customer of my two store on a single site.
