### ISSUE TITLE
Add ability to specify site_id for each call, overriding the global value

### ISSUE THREAD

**Issue by stevehanson** [wingrunr21/mindbody-api#39]
I work for a SaaS studio-membership company, and we use this gem to allow our members to book classes at any MindBody studio that we partner with.

This gem currently has a globally-set `site_id` that is used for each API call, which makes it difficult to use this gem to interface with multiple studios. I've monkey-patched my version of this gem to allow overriding the `site_id` on any request by passing in a `site_id` param as a local when making the request, eg:

```ruby
MindBody::Services::SaleService.checkout_shopping_cart(site_id: "123456", ...)
```

I was wondering if this is functionality you'd be interested in including in this gem, and if so, would be happy to start a discussion in this thread and submit a PR once an approach is decided on. If not, no worries either.

**Comment by wingrunr21** [comment]
You mean via #17 when we discussed this previously? 😄 

I'm going to close this issue but I'm happy to discuss further in #17.

**Comment by stevehanson** [comment]
Hah, wow, completely forgot about that 😄
